# Generated by Django 5.1 on 2024-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
